### ISSUE TITLE
Which version of RoH is this made to be compatible with?

### ISSUE THREAD

**Issue by dmrickey** [Lost-Outpost/Septimus-ROH#1]
The readme just links to the mod page, it doesn't say which specific version this was created against. Can you add that information to the readme?

**Comment by Webmetz** [comment]
It is on the release page when you download the add-on.  Each download is labeled with the version number is was made with

**Comment by dmrickey** [comment]
> It is on the release page when you download the add-on. Each download is labeled with the version number is was made with

Well yeah I know the RoH files list which version they are, my point was that I don't know which version to download because I'm not seeing that listed anywhere here.

Clicking around more now I'm guessing you're talking about the releases _here_ and not the RoH releases. The readme doesn't have that info plainly available. Especially since that information is found in step 4 but is needed in step 1. 

It would be helpful to either move the "download this" for step 4 up to the first step or have a note in the current step 1 that says something like "to see the version of RoH refer to the file name from step 4".
